#!/usr/bin/env python
#
# YAML to C headers generator
#
# Copyright (c) 2012 chrysn <chrysn@fsfe.org>
# Copyright (c) 2013 Paul Sokolovsky <pfalcon@users.sourceforge.net>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
# 3. Neither the name of the authors nor the names of other contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

import sys
import os
import yaml
import logging
import textwrap
import glob
import argparse


USE_LIBOPENCM3 = 0

def length2type(bits):
    return {8: "uint8_t", 16: "uint16_t", 32: "uint32_t"}[bits]

def commentblock(*textblocks, **formatargs):
    ret = []
    nowrapcommands = set("@defgroup")
    ret.extend(textwrap.wrap(textblocks[0].format(**formatargs), 80, initial_indent="/** ", subsequent_indent=" * "))
    last_block_was_at = textblocks[0].startswith('@')
    for b in textblocks[1:]:
        formatted = b.format(**formatargs)

        if not (last_block_was_at and b.startswith('@')):
            ret.append(" *")
        if any(b.startswith(c) for c in nowrapcommands):
            ret.append(" * " + formatted)
        else:
            ret.extend(textwrap.wrap(formatted, 80, initial_indent=" * ", subsequent_indent=" * "))
        last_block_was_at = b.startswith('@')
    return "\n".join(ret) + "\n */\n"

def add_defaults(data):
    reg_defaults = data.get('register defaults', {})
    for regdata in data['registers']:
        for k, v in reg_defaults.iteritems():
                if k not in regdata:
                    regdata[k] = v

def load_inherit(fname):
    data = yaml.load(open(os.path.join(base_dir, fname + ".yaml")))
    add_defaults(data)
    regs = data['registers']
    for i in data.get('inherit', []):
        regs += load_inherit(i)
    return regs



def load_yaml(fname):
    "Load yaml file and do basic structural processing."
    data = yaml.load(open(fname))
    add_defaults(data)
    for i in data.get('inherit', []):
        data['registers'] += load_inherit(i)
    # some defaults
    data.setdefault("projectname", "libperipha")
    data.setdefault("includeguard", "LIBPERIPHA_%s_H"%data['shortdocname'])
    data.setdefault("baseref", "?baseref?")
    data.setdefault("registers_baserefext", "?registers_baserefext?")
    data.setdefault("ingroup", "?ingroup?")
    return data


reserved_cnt = 0
def yaml2h(filenamebase, as_struct=False):
    global reserved_cnt
    headername = "%s.h"%filenamebase
    yamlname = "%s.yaml"%filenamebase
    conveniencename = "%s.convenienceheaders"%filenamebase

    logging.info("Generating %s from %s", headername, yamlname)

    data = load_yaml(yamlname)

    if not as_struct:
        blocks = data.get('blocks', [])
        if len(blocks) > 1:
            print "Error: flat definition format not supported when there are more than 1 instance of component"
            sys.exit(1)
        if len(blocks) == 1 and blocks[0]["name"] != data["shortname"]:
            print "Error: flat definition format requires instance of component to have the same name as component"
            sys.exit(1)

    with open(headername, 'w') as outfile:
        def wc(*args, **kwargs): # wrap "outfile" and "data" (as default) arguments  -- i'm a lazy typer
            final_kwargs = data.copy()
            final_kwargs.update(kwargs)
            outfile.write(commentblock(*args, **final_kwargs))
        def wc_close():
            outfile.write("/** @} */\n")
        def nl(): outfile.write("\n")
        def define(key, value, comment=None):
            outfile.write("#define ")
            outfile.write(key)
            outfile.write(" "*max(24-len(key), 1))
            outfile.write(str(value))
            if comment is not None:
                outfile.write(" /**< %s */"%comment)
            nl()
        def struct_field(access, length, num_elements, key, comment=None):
            outfile.write("__" + access + " ")
            outfile.write(length2type(length) + " ")
            outfile.write(key)
            if num_elements != 1:
                outfile.write("[%d]" % num_elements)
            outfile.write(";")
            if comment is not None:
                outfile.write(" /**< %s */"%comment)
            nl()
        def struct_reserved(byte_size, type_len=32):
            global reserved_cnt
            assert byte_size % ((type_len / 8)) == 0
            outfile.write("%s RESERVED%d[%d];" % (length2type(type_len), reserved_cnt, byte_size / (type_len / 8)))
            nl()
            reserved_cnt += 1

        outfile.write(licensedata[data['license']].format(**data))

        if as_struct:
            outfile.write("#include <libperipha_types.h>")
            nl()

        nl()
        wc("@file", "@see {shortdocname}")
        nl()
        wc("Definitions for the {shortname} subsystem ({longname}).", "This corresponds to the description in {baseref}.", "@ingroup {ingroup}", "@defgroup {shortdocname} {shortname} ({longname})", "@{{")
        nl()
        outfile.write("#ifndef {includeguard}\n#define {includeguard}\n".format(**data))
        nl()
        if USE_LIBOPENCM3:
            outfile.write("#include <libopencm3/cm3/common.h>\n#include <libopencm3/efm32/memorymap.h>\n")
            nl()
        wc("Register definitions and register value definitions for the {shortname} subsystem", "@defgroup {shortdocname}_regsandvals {shortname} registers and values", "@{{")
        nl()

        regs = data['registers']

        for template in data.get('templateregs', []):
            template['is_template'] = []
            regs.append(template)

        regs_dict = dict((x['name'], x) for x in regs) # for easier access. they've got to be a list in yaml to preserve order

        wc("These definitions reflect {baseref}{registers_baserefext}", "@defgroup {shortdocname}_registers {shortname} registers", "@{{")
        nl()

        if as_struct:
            outfile.write("typedef struct " + data['shortname'] + "__ {");
            nl()

        reserved_cnt = 0
        offset = 0

        regs.sort(lambda a, b: cmp(a["offset"], b["offset"]))

        for regdata in regs:
            has_bits = "fields" in regdata
            has_values = "values" in regdata
            is_template = "is_template" in regdata
            if is_template:
                # this isn't a real register, just a template
                continue

            assert regdata["offset"] >= offset, regdata
            if as_struct and regdata["offset"] > offset:
                struct_reserved(regdata["offset"] - offset)
            # Calculate offset of next field right away
            offset = regdata["offset"] + regdata.get('length', 32) / 8 * regdata.get('array', 1)

            secondcomponent_name = regdata['name']
            if (has_bits and isinstance(regdata['fields'], str)) or (has_values and isinstance(regdata['values'], str)):
                # uses a template
                secondcomponent_name = regdata['fields'] if has_bits else regdata['values']
                regs_dict[secondcomponent_name]['is_template'].append(regdata['name'])

            comment = None
            if has_bits or has_values:
                comment = "@see %s_%s_%s" % (data['shortdocname'], secondcomponent_name, 'values' if 'values' in regdata else 'bits')

            if as_struct:
                if 'length' not in regdata:
                    print "Warning: register %s lacks 'length' property, assumed 32" % regdata['name']
                if 'access' not in regdata:
                    print "Warning: register %s lacks 'access' property, assumed 'rw'" % regdata['name']
                struct_field(regdata.get('access', 'rw'),
                             regdata.get('length', 32),
                             regdata.get('array', 1),
                             regdata['name'], comment)
            else:
                define("%s_%s" % (data['shortname'], regdata['name']),
                       "MMIO32(%s_BASE + %#.003x)" % (data['shortname'], regdata['offset']),
                       comment)

        if as_struct:
            outfile.write("} " + data['shortname'] + "_Type;");
            nl()

        nl()
        wc_close() # close register definitions
        nl()

        for regdata in regs:
            has_bits = "fields" in regdata
            has_values = "values" in regdata
            is_template = "is_template" in regdata
            if not has_bits and not has_values:
                continue

            data.setdefault("definition_baserefext", "?definition_baserefext?")

            if (has_bits and isinstance(regdata['fields'], str)) or (has_values and isinstance(regdata['values'], str)):
                # uses a template, doesn't need own section
                continue

            commentlines = []
            if is_template:
                commentlines.append("%s for the {shortname} \"{name}\" group of registers (%s)"%("Bit states" if has_bits else "Values", ", ".join(regdata['is_template'])))
                assert len(regdata['is_template']) > 0, "What should I talk about when nobody uses this template?"
                if 'override_backref' in regdata:
                    commentlines.append(regdata['override_backref'])
                else:
                    commentlines.append("These registers use this:")
                    commentlines.append("<ul>") # FIXME: once we're using markdown 1.8, this can be changed to markdown
                    for user in regdata['is_template']:
                        userdata = regs_dict[user]
                        # FIXME: this is an ugly hack around this being in a single wc() line which doesn't take per-line contexts
                        mergeddata = data.copy()
                        mergeddata.update(userdata)
                        commentlines.append(("<li>The {shortname}_{name} register; see {baseref}{definition_baserefext} for definitions"+regdata.get("details", "."+"</li>")).format(**mergeddata))
                    commentlines.append("</ul>")
                commentlines.append('@defgroup {shortdocname}_{name}_%s {shortname} {name} %s'%(('bits' if has_bits else 'values', 'bits group' if has_bits else 'values group')))
            else:
                commentlines.append("%s for the {shortname}_{name} register"%("Bit states" if has_bits else "Values"))
                commentlines.append("See {baseref}{definition_baserefext} for definitions"+regdata.get("details", "."))
                commentlines.append('@defgroup {shortdocname}_{name}_%s {shortname} {name} %s'%(('bits' if has_bits else 'values',)*2))
            commentlines.append('@{{')
            wc(*commentlines, **regdata)
            nl()

            if has_bits:
                for field in regdata['fields']:
                    #shiftdefine = "_%s_%s_%s_shift"%(shortname, regdata['name'], field['name'])
                    #define(shiftdefine, field['shift'])

                    # there is one condition under which field's doc would get shown; show it immediately otherwise
                    if 'doc' in field and not ("values" not in field and field.get("length", 1) == 1):
                        wc(field['doc'])

                    if "values" in field:
                        for value in field.get("values"):
                            define("%s_%s_%s_%s"%(data['shortname'], regdata['name'], field['name'], value['name']), value['value'] if "mask" in field else "(%s<<%s)"%(value['value'], field['shift']), value.get('doc', None))
                    else:
                        if field.get('length', 1) == 1:
                            define("%s_%s_%s"%(data['shortname'], regdata['name'], field['name']), "(1<<%s)"%field['shift'], field.get('doc', None))
                        else:
                            # FIXME: this should require the 'type' parameter to be set on this field
                            pass

                    if "values" in field or field.get("length", 1) != 1:
                        if "mask" in field:
                            mask = field['mask']
                        else:
                            mask = "(%#x<<%s)"%(~(~0<<field.get('length', 1)), field['shift'])
                        define("%s_%s_%s_mask"%(data['shortname'], regdata['name'], field['name']), mask)
                        define("%s_%s_%s_shift"%(data['shortname'], regdata['name'], field['name']), field['shift'])
            else:
                for value in regdata['values']:
                    define("%s_%s_%s"%(data['shortname'], regdata['name'], value['name']), value['value'], value.get('doc', None))

            nl()
            wc_close()
            nl()
        wc_close() # close registers and values
        nl()

        for comp in data.get('blocks', []):
            outfile.write("#define %s_BASE %#x\n" % (comp["name"], comp["base"]))

        if as_struct:
            for comp in data.get('blocks', []):
                outfile.write("#define %s ((%s_Type*)%s_BASE)\n" % (comp['name'], data['shortname'], comp['name']))

        if os.path.isfile(conveniencename):
            outfile.write(open(conveniencename).read())

        nl()
        wc_close() # close convenience
        nl()
        outfile.write("#endif\n")

def c_comment_to_py(lines):
    out = []
    for line in lines.split('\n'):
        if line[0:2] == '/*':
            continue
        elif line[0:3] == ' */':
            continue
        elif line[0:2] == ' *':
            out.append('#' + line[2:])
    return '\n'.join(out)

def yaml2uctypes(filenamebase, as_struct=False):
    global reserved_cnt
    uctypesname = "%s.py" % filenamebase
    yamlname = "%s.yaml" % filenamebase

    logging.info("Generating %s from %s", uctypesname, yamlname)

    data = load_yaml(yamlname)

    with open(uctypesname, 'w') as outfile:
        def nl(): outfile.write("\n")
        outfile.write(c_comment_to_py(licensedata[data['license']].format(**data)))
        nl()
        nl()
        outfile.write('import uctypes')
        nl()
        nl()
        outfile.write('{shortname} = {{'.format(**data))
        nl()
        regs = data['registers']
        regs.sort(lambda a, b: cmp(a["offset"], b["offset"]))
        for regdata in regs:
            has_bits = "fields" in regdata
            is_template = "is_template" in regdata
            if is_template:
                # this isn't a real register, just a template
                continue
            if 'length' not in regdata:
                print "Warning: register %s lacks 'length' property, assumed 32" % regdata['name']
            outfile.write("    '{:s}': ".format(regdata['name']))
            if has_bits:
                outfile.write('(0x{:x}, {{'.format(regdata.get('offset')))
                nl()
                max_width = max(len(field['name']) for field in regdata['fields'])
                for field in regdata['fields']:
                    outfile.write("        '{:s}':{:s} uctypes.BFUINT{:d} | 0x{:02x} | {:2d} << 17 | {:2d} << 22,".format(field['name'],
                                                                                                                      ' ' * (max_width - len(field['name'])),
                                                                                                                 regdata.get('length', 32),
                                                                                                                 regdata.get('offset'),
                                                                                                                 field['shift'],
                                                                                                                 field.get('length', 1)))
                    nl()
                outfile.write('    }),')
            else:
                outfile.write('uctypes.UINT{:d} | 0x{:02x},'.format(regdata.get('length', 32),
                                                                regdata.get('offset')))
            nl()
        outfile.write('}')
        nl()


def find_base_dir():
    cur_path = "."
    while True:
        abs_path = os.path.abspath(cur_path)
        if abs_path == "/":
            return None
        if os.path.exists(abs_path + "/licenses.yaml"):
            return abs_path
        cur_path = "../" + cur_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='yaml2h.py',
        usage='%(prog)s [options]',
        description='Generate header file from a register definition'
    )
    parser.add_argument(
        '--uctypes',
        dest='gen_uctypes',
        action='store_true',
        help='Generate MicroPython uctypes source rather than header files',
    )
    args = parser.parse_args(sys.argv[1:])

    logging.basicConfig(level=logging.DEBUG)
    base_dir = find_base_dir()
    if not base_dir:
        print "Cannot find licenses.yaml in current/parent dirs"
        sys.exit(1)
    licensedata = yaml.load(open(os.path.join(base_dir, "licenses.yaml")))
    processed = False
    for fname in glob.glob("*.yaml"):
        basename = os.path.splitext(fname)[0]
        if basename == "licenses":
            continue
        if args.gen_uctypes:
            yaml2uctypes(basename, True)
        else:
            yaml2h(basename, True)
        processed = True

    if not processed:
        print "Run this script in a directory with .yaml register descriptions"
